[workspace]
members = [
	"smpl",
	"smplc",
	"smpli",
	"examples/tic-tac-toe",
]
exclude = [
	"smpl-tests/target/sample_program",
	"smpl-tests/target/basic_tests",
]

[patch.crates-io]
smpl = { path = "./smpl" }
