[package]
name = "smplc"
version = "0.1.0"
authors = ["Alexander Vo <randomcivvy0121@gmail.com>"]
workspace = ".."

[dependencies]
smpl = { path = "../smpl/" }
clap = { version = "2.29.1", features = ["yaml"]}
ascii = "0.8.6"
