[package]
name = "smpl"
version = "0.1.2"
authors = ["Alexander Vo <randomcivvy0121@gmail.com>"]
workspace = ".."

description = "Core library to compile the SMPL language"

license="MIT"
repository="https://github.com/InnPatron/smpl-mirror"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
itertools = "0.6.3"
ascii = "0.8.6"
lalrpop-util = "0.13.1"
regex = "0.2.1"
petgraph = "0.4.9"
irmatch = "0.2.0"
