[package]
name = "smpl"
version = "0.12.0"
authors = ["Alexander Vo <randomcivvy0121@gmail.com>"]
workspace = ".."
edition = "2018"

description = "Core library to compile the SMPL language"

license="MIT"
repository="https://github.com/InnPatron/smpl-mirror"

[dependencies]
itertools = "0.6.3"
regex = "0.2.1"
petgraph = "0.4.9"
irmatch = "0.2.0"
strfmt = "0.1.6"
failure = "0.1.2"
failure_derive = "0.1.2"
uuid = { version = "0.7", features = ["v4"] }
derive_builder = "0.7.0"
